version: "3.9"
services:
    web:
        build: ./web_server
        ports:
         - "80:80"
    client:
        build: ./python_client       
        volumes:
         - ./docker_data:/data
        environment:
         - HOST_IP=web
        deploy:
            replicas: 10
