version: "3.9"
services:
    web:
        build: ./web_server
    client:
        build: ./python_client       
        volumes:
         - ./docker_data:/data
        environment:
         - HOST_IP=web
        deploy:
            replicas: 80
    malicious_client:
        build: ./python_client
        volumes:
         - ./docker_data:/data
        environment:
         - HOST_IP=web
         - CLIENT_TYPE=1
